services:
  minio:
    ports:
      - 9001:9001
      - 9000:9000
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"
    volumes:
      - s3:/data

  
volumes:
  s3:
    driver: local