import type {Metadata} from "next";
import localFont from "next/font/local";
import "@/app/globals.css"
import {ThemeProvider} from "@/components/layout/theme-provider";
import {Toaster} from "@/components/ui/toaster";
import AudioComponent from "@/components/layout/audio";
import AuthProvider from "./(auth)/auth/_components/context";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            themes={["light", "dark"]}
            enableSystem
            disableTransitionOnChange
        >

            <AuthProvider>
                {children}
            </AuthProvider>
        </ThemeProvider>
        <Toaster/>
        <AudioComponent/>
        </body>
        </html>
    );
}
